services:
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    image: backpackr/activity-sessionization:1.0.0
    environment:
      DRIVER_MEMORY: ${DRIVER_MEMORY:-4g}
      SPARK_MASTER: local[*]
    volumes:
      - ./data:/opt/app/data
      - ./conf:/opt/app/conf
      - ./metastore_db:/opt/app/metastore_db
      - ./spark-warehouse:/opt/app/spark-warehouse
    working_dir: /opt/app
    command:
      - --mode
      - ingest
      - --config
      - /opt/app/conf/local.properties
      - --start-date
      - "2019-10-01"
      - --end-date
      - "2019-11-30"
